image:
    - Visual Studio 2019
version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk15

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - java -version
  - gradlew.bat --version
build_script:
  - gradlew.bat -i assemble
test_script:
  - gradlew.bat -i -S check
